package com.iudigital.cruddao.Presentacion;


import com.iudigital.cruddao.Controller.FuncionarioController;
import com.iudigital.cruddao.domain.Funcionario;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {
    
    private final FuncionarioController funcionarioController;
    private static final String[] COLUMNS = {"ID", "N°DOCUMENTO", "NOMBRES", "APELLIDOS", 
        "SEXO", "DIRECCION","TELEFONO","FECHA NACIMIENTO","ESTADO CIVIL"};
    private static final String SELECCIONE = "--SELECCIONE--";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        txtFunId.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFUNC();
        addListener();
    }
    
    private void listFUNC() {
        cbxFunc.removeAllItems();
        Funcionario FuncionarioCombo =  new Funcionario();
        FuncionarioCombo.setNumero_identificacion(SELECCIONE);
        FuncionarioCombo.setNombres("");
        cbxFunc.addItem(FuncionarioCombo);
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for (String COLUMN : COLUMNS) {
            defaultTableModel.addColumn(COLUMN);
        }
        
        tblFunci.setModel(defaultTableModel);
        try {
            List<Funcionario> funcionarios = funcionarioController.obtenerFuncionarios();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionarios.size());
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getFuncionario_id(), row, 0);
                defaultTableModel.setValueAt(funcionario.getNumero_identificacion(), row, 1);
                defaultTableModel.setValueAt(funcionario.getNombres(), row, 2);
                defaultTableModel.setValueAt(funcionario.getApellidos(), row, 3);
                defaultTableModel.setValueAt(funcionario.getSexo(), row, 4);
                defaultTableModel.setValueAt(funcionario.getDireccion(), row, 5);
                defaultTableModel.setValueAt(funcionario.getTelefono(), row, 6);
                defaultTableModel.setValueAt(funcionario.getFecha_nacimiento(), row, 7);
                defaultTableModel.setValueAt(funcionario.getEstado_civil(), row, 8);
                row++;
                
                cbxFunc.addItem(funcionario);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void addListener() {
        cbxFunc.addItemListener(event -> {
             Funcionario selectedFUN = (Funcionario) event.getItem();
            if (selectedFUN.getNumero_identificacion().equals(SELECCIONE)) {
                txtFunId.setText("");
                txtDOCEdit.setText("");
                txtNOMBRESEdit.setText("");
                txtAPELLIDOSEdit.setText("");
                txtSEXOEdit.setText("");
                txtDIRECCIONEdit.setText("");
                txtTELEFONOEdit.setText("");
                txtFECHAEdit.setText("");
                txtESTADOEdit.setText("");
            } else {
                txtFunId.setText(String.valueOf(selectedFUN.getFuncionario_id()));
                txtDOCEdit.setText(selectedFUN.getNumero_identificacion());
                txtNOMBRESEdit.setText(selectedFUN.getNombres());
                txtAPELLIDOSEdit.setText(selectedFUN.getApellidos());
                txtSEXOEdit.setText(selectedFUN.getSexo());
                txtDIRECCIONEdit.setText(selectedFUN.getDireccion());
                txtTELEFONOEdit.setText(selectedFUN.getTelefono());
                txtFECHAEdit.setText(selectedFUN.getFecha_nacimiento());
                txtESTADOEdit.setText(selectedFUN.getEstado_civil());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanels = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPCar = new javax.swing.JPanel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTransmision = new javax.swing.JLabel();
        txtDOC = new javax.swing.JTextField();
        txtNOMBRES = new javax.swing.JTextField();
        txtAPELLIDOS = new javax.swing.JTextField();
        txtSEXO = new javax.swing.JTextField();
        txtDIRECCION = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtFECHA = new javax.swing.JTextField();
        txtTELEFONO = new javax.swing.JTextField();
        txtESTADO = new javax.swing.JTextField();
        lblBrand1 = new javax.swing.JLabel();
        lblBrand2 = new javax.swing.JLabel();
        lblBrand3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFunci = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxFunc = new javax.swing.JComboBox<>();
        lblfunId = new javax.swing.JLabel();
        lblBrandEdit = new javax.swing.JLabel();
        lblModelEdit = new javax.swing.JLabel();
        lblYearEdit = new javax.swing.JLabel();
        lblColorEdit = new javax.swing.JLabel();
        lblTransmisionEdit = new javax.swing.JLabel();
        txtFunId = new javax.swing.JTextField();
        txtDOCEdit = new javax.swing.JTextField();
        txtNOMBRESEdit = new javax.swing.JTextField();
        txtAPELLIDOSEdit = new javax.swing.JTextField();
        txtSEXOEdit = new javax.swing.JTextField();
        txtDIRECCIONEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtTELEFONOEdit = new javax.swing.JTextField();
        txtFECHAEdit = new javax.swing.JTextField();
        txtESTADOEdit = new javax.swing.JTextField();
        lblTransmisionEdit1 = new javax.swing.JLabel();
        lblTransmisionEdit2 = new javax.swing.JLabel();
        lblTransmisionEdit3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setText(" GESTIÓN DE FUNCIONARIOS IUDIGITAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 210, 30));

        jPCar.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblBrand.setText(" Cc.Doc");

        lblModel.setText(" NOMBRES");

        lblYear.setText(" APELLIDOS");

        lblColor.setText(" SEXO");

        lblTransmision.setText(" DIRECCION");

        txtDOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOCActionPerformed(evt);
            }
        });

        btnCreate.setText("GUARDAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtFECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFECHAActionPerformed(evt);
            }
        });

        txtTELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTELEFONOActionPerformed(evt);
            }
        });

        txtESTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtESTADOActionPerformed(evt);
            }
        });

        lblBrand1.setText(" TELEFONO");

        lblBrand2.setText("  FECHA.NACIMIENTO");

        lblBrand3.setText(" ESTADO CIVIL");

        javax.swing.GroupLayout jPCarLayout = new javax.swing.GroupLayout(jPCar);
        jPCar.setLayout(jPCarLayout);
        jPCarLayout.setHorizontalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand)
                    .addComponent(txtTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel)
                    .addComponent(txtNOMBRES, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCarLayout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTransmision)
                            .addComponent(txtDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColor)
                            .addComponent(txtSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(164, 164, 164))
        );
        jPCarLayout.setVerticalGroup(
            jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(lblYear)
                    .addComponent(lblColor)
                    .addComponent(lblModel))
                .addGap(3, 3, 3)
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOMBRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCarLayout.createSequentialGroup()
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBrand1)
                            .addComponent(lblBrand2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCarLayout.createSequentialGroup()
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTransmision)
                            .addComponent(lblBrand3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(btnCreate)
                .addContainerGap())
        );

        tblFunci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFunci.setToolTipText("");
        jScrollPane2.setViewportView(tblFunci);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanels.addTab("Crear Funcionario", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifique los siguientes campos"));

        jLabel2.setText("     Funcionarios");

        cbxFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncActionPerformed(evt);
            }
        });

        lblfunId.setText("ID");

        lblBrandEdit.setText("  N° Documento");

        lblModelEdit.setText(" Nombres");

        lblYearEdit.setText(" Apellidos");

        lblColorEdit.setText("Sexo");

        lblTransmisionEdit.setText("Direccion");

        txtNOMBRESEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOMBRESEditActionPerformed(evt);
            }
        });

        btnEdit.setText("ACTUALIZAR");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("ELIMINAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTransmisionEdit1.setText(" Telefono");

        lblTransmisionEdit2.setText("  Fecha Nacimiento");

        lblTransmisionEdit3.setText(" Estado Civil ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFunId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblfunId)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrandEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOCEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnEdit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNOMBRESEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTransmisionEdit)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(lblYearEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDIRECCIONEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAPELLIDOSEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtESTADOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblColorEdit)
                                .addComponent(lblTransmisionEdit3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtSEXOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblTransmisionEdit1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtTELEFONOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFECHAEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTransmisionEdit2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfunId)
                    .addComponent(lblBrandEdit)
                    .addComponent(lblModelEdit)
                    .addComponent(lblYearEdit)
                    .addComponent(lblColorEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFunId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOCEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNOMBRESEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAPELLIDOSEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSEXOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransmisionEdit1)
                    .addComponent(lblTransmisionEdit2)
                    .addComponent(lblTransmisionEdit3)
                    .addComponent(lblTransmisionEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTELEFONOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFECHAEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtESTADOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDIRECCIONEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanels.addTab("Actualizar Funcionario", jPanel2);

        getContentPane().add(jPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncActionPerformed

    private void txtNOMBRESEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOMBRESEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOMBRESEditActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        if (txtDOC.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite N°Documento");
            txtDOC.requestFocus();
            return;
        }

        if (txtNOMBRES.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombres");
            txtNOMBRES.requestFocus();
            return;
        }

        if (txtAPELLIDOS.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtAPELLIDOS.requestFocus();
            return;
        }

        if (txtSEXO.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Sexo");
            txtSEXO.requestFocus();
            return;
        }

        if (txtDIRECCION.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Direccion");
            txtDIRECCION.requestFocus();
            return;
        }
        if (txtTELEFONO.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Telefono");
            txtTELEFONO.requestFocus();
            return;
        }
         if (txtFECHA.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Fecha nacimiento");
            txtFECHA.requestFocus();
            return;
        }
         if (txtESTADO.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Estado civil");
            txtESTADO.requestFocus();
            return;
        }
        try {

            Funcionario funcionario = new Funcionario();
            funcionario.setNumero_identificacion(txtDOC.getText().trim());
            funcionario.setNombres(txtNOMBRES.getText().trim());
            funcionario.setApellidos(txtAPELLIDOS.getText().trim());
            funcionario.setSexo(txtSEXO.getText().trim());
            funcionario.setDireccion(txtDIRECCION.getText().trim());
            funcionario.setTelefono(txtTELEFONO.getText().trim());
            funcionario.setFecha_nacimiento(txtFECHA.getText().trim());
            funcionario.setEstado_civil(txtESTADO.getText().trim());
            funcionarioController.crear(funcionario);
            txtDOC.setText("");
            txtNOMBRES.setText("");
            txtAPELLIDOS.setText("");
            txtSEXO.setText("");
            txtDIRECCION.setText("");
            txtTELEFONO.setText("");
            txtFECHA.setText("");
            txtESTADO.setText("");
            listFUNC();
            JOptionPane.showMessageDialog(null, "Funcionario creado con éxito");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "No se pudo crear el Funcionario");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtDOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOCActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if (txtFunId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un funcionario de la lista");
            txtFunId.requestFocus();
            return;
        }

        if (txtDOCEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite N°Documento");
            txtDOCEdit.requestFocus();
            return;
        }

        if (txtNOMBRESEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Nombres");
            txtNOMBRESEdit.requestFocus();
            return;
        }

        if (txtAPELLIDOSEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Apellidos");
            txtAPELLIDOSEdit.requestFocus();
            return;
        }

        if (txtSEXOEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Sexo");
            txtSEXOEdit.requestFocus();
            return;
        }

        if (txtDIRECCIONEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Direccion");
            txtDIRECCIONEdit.requestFocus();
            return;
        }
        if (txtTELEFONOEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Telefono");
            txtTELEFONOEdit.requestFocus();
            return;
        }
         if (txtFECHAEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Fecha nacimiento");
            txtFECHAEdit.requestFocus();
            return;
        }
         if (txtESTADOEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite Estado civil");
            txtESTADOEdit.requestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setNumero_identificacion(txtDOCEdit.getText().trim());
        funcionario.setNombres(txtNOMBRESEdit.getText().trim());
        funcionario.setApellidos(txtAPELLIDOSEdit.getText().trim());
        funcionario.setSexo(txtSEXOEdit.getText().trim());
        funcionario.setDireccion(txtDIRECCIONEdit.getText().trim());
        funcionario.setTelefono(txtTELEFONOEdit.getText().trim());
        funcionario.setFecha_nacimiento(txtFECHAEdit.getText().trim());
        funcionario.setEstado_civil(txtESTADOEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "Desea actualizar el funcionario", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {

            try {
                funcionarioController.actualizarFuncionario(Integer.parseInt(txtFunId.getText()), funcionario);
                txtDOCEdit.setText("");
                txtNOMBRESEdit.setText("");
                txtAPELLIDOSEdit.setText("");
                txtSEXOEdit.setText("");
                txtDIRECCIONEdit.setText("");
                txtTELEFONOEdit.setText("");
                txtFECHAEdit.setText("");
                txtESTADOEdit.setText("");
                listFUNC();
                JOptionPane.showMessageDialog(null, "Se ha actualizado el funcionario con exito");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el funcionario");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (txtFunId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un funcionario de la lista");
            txtFunId.requestFocus();
            return;
        }
        
        int opt = JOptionPane.showConfirmDialog(null, "Está seguro que desea eliminar el funcionario",
                "Confirmar salida", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {

            try {
                funcionarioController.eliminarFuncionario(Integer.parseInt(txtFunId.getText()));
                txtDOCEdit.setText("");
                txtNOMBRESEdit.setText("");
                txtAPELLIDOSEdit.setText("");
                txtSEXOEdit.setText("");
                txtDIRECCIONEdit.setText("");
                txtTELEFONOEdit.setText("");
                txtFECHAEdit.setText("");
                txtESTADOEdit.setText("");
                listFUNC();
                JOptionPane.showMessageDialog(null, "Se eliminó el funcionario correctamente");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el funcionario");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtFECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFECHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFECHAActionPerformed

    private void txtTELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTELEFONOActionPerformed

    private void txtESTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtESTADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtESTADOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<Funcionario> cbxFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jPanels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrand1;
    private javax.swing.JLabel lblBrand2;
    private javax.swing.JLabel lblBrand3;
    private javax.swing.JLabel lblBrandEdit;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorEdit;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModelEdit;
    private javax.swing.JLabel lblTransmision;
    private javax.swing.JLabel lblTransmisionEdit;
    private javax.swing.JLabel lblTransmisionEdit1;
    private javax.swing.JLabel lblTransmisionEdit2;
    private javax.swing.JLabel lblTransmisionEdit3;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYearEdit;
    private javax.swing.JLabel lblfunId;
    private javax.swing.JTable tblFunci;
    private javax.swing.JTextField txtAPELLIDOS;
    private javax.swing.JTextField txtAPELLIDOSEdit;
    private javax.swing.JTextField txtDIRECCION;
    private javax.swing.JTextField txtDIRECCIONEdit;
    private javax.swing.JTextField txtDOC;
    private javax.swing.JTextField txtDOCEdit;
    private javax.swing.JTextField txtESTADO;
    private javax.swing.JTextField txtESTADOEdit;
    private javax.swing.JTextField txtFECHA;
    private javax.swing.JTextField txtFECHAEdit;
    private javax.swing.JTextField txtFunId;
    private javax.swing.JTextField txtNOMBRES;
    private javax.swing.JTextField txtNOMBRESEdit;
    private javax.swing.JTextField txtSEXO;
    private javax.swing.JTextField txtSEXOEdit;
    private javax.swing.JTextField txtTELEFONO;
    private javax.swing.JTextField txtTELEFONOEdit;
    // End of variables declaration//GEN-END:variables
}
